// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // ATENÇÃO: Para o Web funcionar, você precisa configurar um Web App no Firebase Console
      // e substituir os valores abaixo ou executar 'flutterfire configure'.
      return const FirebaseOptions(
        apiKey: 'AIzaSyCaB79yJSec7W8RWjvZIBOqgWOEagP-6Z4',
        appId: '1:486304722185:web:substitua_pelo_seu_web_app_id',
        messagingSenderId: '486304722185',
        projectId: 'ivalid-9396b',
        authDomain: 'ivalid-9396b.firebaseapp.com',
        storageBucket: 'ivalid-9396b.firebasestorage.app',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaB79yJSec7W8RWjvZIBOqgWOEagP-6Z4',
    appId: '1:486304722185:android:73431616c6045979cbf7d8',
    messagingSenderId: '486304722185',
    projectId: 'ivalid-9396b',
    storageBucket: 'ivalid-9396b.firebasestorage.app',
  );
}
